### ISSUE TITLE
error in build.bat building on fresh install

### ISSUE THREAD

**Issue by mikeestee** [NVIDIA-Omniverse/kit-app-template#4]
Running in powershell, I get the following error when trying to build.

`PS Z:\github\ov-kit-helloworld> .\build.bat
Setting user environment variable PM_PACKAGES_ROOT to Z:\packman-repo

SUCCESS: Specified value was saved.
Traceback (most recent call last):
  File "Z:\github\ov-kit-helloworld\tools\repoman\repoman.py", line 25, in <module>
    bootstrap()
  File "Z:\github\ov-kit-helloworld\tools\repoman\repoman.py", line 18, in bootstrap
    deps = packmanapi.pull(REPO_DEPS_FILE)
  File "Z:\packman-repo\packman-common\6.42\packman\utils.py", line 506, in wrapper_message_block
    return func(*args, **kwargs)
  File "Z:\packman-repo\packman-common\6.42\packman\main.py", line 1175, in pull
    project_path, platform, postscript, remotes, include_tags, exclude_tags, tokens
  File "Z:\packman-repo\packman-common\6.42\packman\main.py", line 1198, in pull_with_variable_file
    deps = project.get_dependencies(platform, include_tags, exclude_tags)
  File "Z:\packman-repo\packman-common\6.42\packman\schemaparser.py", line 363, in get_dependencies
    candidate = dep.as_resolved(platform_name, include_tags, exclude_tags)
  File "Z:\packman-repo\packman-common\6.42\packman\schemaparser.py", line 701, in as_resolved
    dep.link_path = _resolve_keyword(self.link_path, platform)
  File "Z:\packman-repo\packman-common\6.42\packman\schemaparser.py", line 53, in _resolve_keyword
    template_resolved = template.substitute(platform=platform_str)
  File "Z:\packman-repo\python\3.7.12-windows-x86_64\lib\string.py", line 132, in substitute
    return self.pattern.sub(convert, self.template)
  File "Z:\packman-repo\python\3.7.12-windows-x86_64\lib\string.py", line 129, in convert
    self._invalid(mo)
  File "Z:\packman-repo\python\3.7.12-windows-x86_64\lib\string.py", line 105, in _invalid
    (lineno, colno))
ValueError: Invalid placeholder in string: line 1, col 10`

**Comment by SchultzC** [comment]
The Kit App Template repository has been updated. To create a simple interactive application, please follow the [Quick Start Section](https://github.com/NVIDIA-Omniverse/kit-app-template/tree/main?tab=readme-ov-file#quick-start) (after verifying system requirements) to build based on the Kit Base Editor Template.
